### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by projectgerdri** [projectgerdri/projectgerdri#2]
Generar la base de datos

**Comment by gerardvisa** [comment]
Adri, un par de comentarios respecto a la BBDD:

- Considero innecesario tener username + nickname. Registrarse con mail y tener un nick es lo más sensato.
- Se podrían añadir dos campos en la tabla Teams para los colores del equipo. Ya que no nos vamos a poner ahora con movidas de equipaciones y tal, creo que tiene sentido que un equipo tenga dos colores que le representen y puedan dar más vidilla a la interfaz de usuario.

Es posible que añada más comentarios mañana ya que no me ha dado tiempo a analizar las tablas Players y Matches.

**Comment by gerardvisa** [comment]
A falta de pequeños cambios, la BBDD ya ha sido creada y está descrita en el documento [https://docs.google.com/document/d/1gtHu-AkTkFxkkQ_FjbjpWOBwgImCTQL26k35uvmG5NA/edit?usp=sharing] (https://docs.google.com/document/d/1gtHu-AkTkFxkkQ_FjbjpWOBwgImCTQL26k35uvmG5NA/edit?usp=sharing)
